### ISSUE TITLE
[progress tracker] tree view backed by nestable selectable evented lists

### ISSUE THREAD

**Issue by alisterburt** [napari/superqt#77]
I'm opening this issue to track progress towards achieving [the following](https://github.com/napari/napari/issues/2229#issuecomment-774541635)

> I can imagine us getting to a place where we could say "you tell us what your tree structure looks like and we'll give you a UI for it".

I think we want the model for this to be a nested set of [`SelectableEventedList`s in psygnal](https://github.com/tlambert03/psygnal/pull/78/files) - in superqt we can provide a view of this model similar to the [`QtTreeView` in napari](https://github.com/napari/napari/blob/main/napari/_qt/containers/qt_tree_view.py#L20-L33)

- [x] tlambert03/psygnal#64 to psygnal
- [ ] tlambert03/psygnal#78
- [ ] add [support for nesting](https://github.com/napari/napari/blob/main/napari/utils/events/containers/_nested_list.py) to the evented list in psygnal
- [ ] make Qt view classes

You can probably tell I'm a little vague on the details in the last step 😆
